### ISSUE TITLE
Unable to Scrape Dynamic Content

### ISSUE THREAD

**Issue by TheBobFather1980** [rflechner/ScrapySharp#28]
I'm trying to use the ScrapingBrowser class to navigate and scrape a site.  I noticed I was unable to enter the username and password on the login page because it is dynamically generated from Javascript.  Is there a way to execute scripts on the page so I can get the full web page content?

**Comment by coolhome** [comment]
@TheBobFather1980 This library only works with server side rendered content (static) because `HtmlAgilityPack` is just an html parser. There is no real browser. You might want to look at something like [Web Driver](https://www.w3.org/TR/webdriver/) which uses a real browser. It should be noted that this approach has a lot more overhead costs.
